import sqlite3, os
DB = os.path.join(os.path.dirname(os.path.abspath(__file__)), "data", "yamen_academy.db")
conn = sqlite3.connect(DB)
c = conn.cursor()
c.execute("""CREATE TABLE IF NOT EXISTS questions (id INTEGER PRIMARY KEY AUTOINCREMENT, skill TEXT NOT NULL, question TEXT NOT NULL, option_a TEXT NOT NULL, option_b TEXT NOT NULL, option_c TEXT NOT NULL, option_d TEXT NOT NULL, correct_answer TEXT NOT NULL, difficulty TEXT DEFAULT 'beginner', created_at TEXT DEFAULT (datetime('now','localtime')), updated_at TEXT DEFAULT (datetime('now','localtime')))""")
c.execute("""CREATE TABLE IF NOT EXISTS placement_results (id INTEGER PRIMARY KEY AUTOINCREMENT, student_id INTEGER, band TEXT, level TEXT, path TEXT, score_pct REAL, taken_at TEXT DEFAULT (datetime('now','localtime')))""")
c.execute("DELETE FROM questions")
conn.commit()
conn.close()
print("DB READY - questions + placement_results tables created, old data cleared")
